nmMode: hardlinks-global
nodeLinker: node-modules
enableGlobalCache: true
globalFolder: "/Users/r0mankon/workSpace/.yarn/global"
cloneConcurrency: 4
progressBarStyle: patrick
plugins:
  - path: /Users/r0mankon/workSpace/.yarn/global/plugins/@yarnpkg/plugin-interactive-tools.cjs
    spec: "@yarnpkg/plugin-interactive-tools"
